### ISSUE TITLE
请问能分享训练集嘛

### ISSUE THREAD

**Issue by hdhhdhhdhhdh** [caiyuanhao1998/MST-plus-plus#1]
您好，您的工作很棒，但是我没有在相关的网页找到训练集，请问您能分享相关的训练级嘛

**Comment by hdhhdhhdhhdh** [comment]
哇，非常感谢了

**Comment by chenjiachengzzz** [comment]
> 我已把谷歌云盘超链接更新在readme里面了。

非常抱歉，请问可以提供百度网盘链接吗

**Comment by caiyuanhao1998** [comment]
百度网盘链接已更新在readme里面了，希望帮到你

**Comment by chenjiachengzzz** [comment]
> 百度网盘链接已更新在readme里面了，希望帮到你

非常感谢，祝您科研顺利！
