### ISSUE TITLE
Params和Flops是如何计算的呀

### ISSUE THREAD

**Issue by Deep-imagelab** [caiyuanhao1998/MST-plus-plus#10]
请问是直接调用工具包了吗？特别是Flops的计算，是以多大尺寸的输入为基准的呀？

**Comment by caiyuanhao1998** [comment]
FLOPS 和 Params 需要对网络进行逐层统计。
现有的包如 torchsummaryX 测出来的 Transformer 都不准。

**Comment by Deep-imagelab** [comment]
> FLOPS 和 Params 需要对网络进行逐层统计。 现有的包如 torchsummaryX 测出来的 Transformer 都不准。

嗯嗯，好的，感谢回复
