### ISSUE TITLE
请问下，我通过cv方法将mat文件转换为的png图片为何是单通道而不是四通道的？

### ISSUE THREAD

**Issue by alwaysquietll** [caiyuanhao1998/MST-plus-plus#13]
import h5py
import cv2
import numpy as np
path = "ARAD_1K_0912.mat"
with h5py.File(path, 'r') as mat:
    hyper = np.float32(np.array(mat['cube']))*255
cv2.imwrite('ARAD_1K_0912.png', hyper[15,:,:])
作者大佬您好，我通过您提供的代码将预测结果的mat文件转换为了png图片，但是想请问下为何转换后的图片只有单通道？不知我是否理解有误，我在介绍里看着好像转换后的高光谱图像是四通道的？可否解答下我的困惑，感谢您了

**Comment by caiyuanhao1998** [comment]
你好，这个代码本身就是取单张图片进行伪彩色渲染。
cv2.imwrite('ARAD_1K_0912.png', hyper[15,:,:])
这和操作本身就是取一个通道(15)进行保存。
如果想存全部的图片，你可以对这一维度进行遍历然后再存图。

**Comment by alwaysquietll** [comment]
感谢解答，还想再问一下，您代码里的mat['cube']就是获取高光谱图像的数据立方体吧？然后通过np.array将其转换为数组，再通过np.float32将其转换为float32类型，又因为彩色通道的数值范围在0~255，所以这里要*255才可以进行伪彩色渲染？

然后您说代码里取的是15通道进行保存，我看在Hyperspectral Viewer里显示的band number是（31，16，7），是否因为保存数据里的通道是从0开始，所以原来的16这里要用15才能取出？想存全部的图片，这里说的遍历我不是很理解，是不是分别用hyper[15,:,:]，hyper[6,:,:]，hyper[30,:,:]取三个通道数据进行写入保存即可？

还有就是通过相关的代码进行的是伪彩色渲染，那么如果要对转换后的高光谱图片进行分析、处理，那么还是用mat文件进行相关操作比较好吧？

最后还有个问题，就是我用Hyperspectral Viewer打开同样生成的mat文件，band number显示的却是（27，17，7），与示例中的不同，这是否正常呢？
![image](https://user-images.githubusercontent.com/43427787/184783758-01bba564-27db-47bb-8c27-435259d00fed.png)

由于对相关知识了解不多，还在努力学习中，问题也比较多，希望您有空的时候帮我解答一下了，谢谢

**Comment by alwaysquietll** [comment]
感谢大佬的耐心解答，对我有很大的帮助，也祝您的后续论文科研进展顺利
