### ISSUE TITLE
HDNet code

### ISSUE THREAD

**Issue by lzw-lzw** [caiyuanhao1998/MST-plus-plus#17]
It seems that the  spatial_attention and spectral_attention(SDL_attention) code implementation of the HDNet is contrary to what you written in the paper

**Comment by caiyuanhao1998** [comment]
What do you mean? Could you please describe your question more specifically?

如果觉得用英文不太好说的话，你也可以讲中文。

**Comment by caiyuanhao1998** [comment]
你想说 Line 241 - Line 285 这一段的 spectral 和 spatial 写反了? 是这个意思吗？不过他俩在forward函数里面是对称的，所以就算位置对调，名字取反了，也没影响，问题不大。

**Comment by lzw-lzw** [comment]
> 对的就是那里写反了 不过不会影响结果

**Comment by caiyuanhao1998** [comment]
嗯嗯，我扫了一眼，好像是这样，不过也没啥影响，HDNet在这个任务上不太行，没太多人关注它，懒得改了。

**Comment by lzw-lzw** [comment]
okk 另外好像Line271-272这里是先qv分支先相乘再softmax 论文里Spatial Attention图片和公式都是先对q这边softmax再和v分支相乘，这个差异不会影响结果吗

**Comment by caiyuanhao1998** [comment]
诶，这个可以做个对比实验试一下，我感觉是几乎没啥影响。为啥你会对 HDNet 这么感兴趣？它是什么地方吸引到你了？

**Comment by lzw-lzw** [comment]
hhh我尝试着复现了您的MST++，然后顺便看了看HRNet，发现有点不一样就问问，谢谢！

**Comment by caiyuanhao1998** [comment]
OK，没事，欢迎你使用我们的代码。如果觉得有帮助的话，麻烦给个 star 并在写paper的时候引一下我们的文章，感谢

**Comment by caiyuanhao1998** [comment]
如果你想找个好一点发论文的方向的话，推荐你去做snapshot compressive imaging，这个方向在2020年才刚刚兴起。在low-level领域里面还不算卷的。我们在另一个repo里面也搞了一个工具包，你可以参考一下

https://github.com/caiyuanhao1998/MST

**Comment by lzw-lzw** [comment]
好的，谢谢您
