### ISSUE TITLE
How .mat to .jpg

### ISSUE THREAD

**Issue by ljf20122010** [caiyuanhao1998/MST-plus-plus#18]
I want to convert the. mat file into a. jpg file, but after the matlab code conversion, all the pictures are black. This is my code.

![code](https://user-images.githubusercontent.com/33053551/191937117-81c184de-205c-4491-a0e7-1ca294c3772c.png)
![show](https://user-images.githubusercontent.com/33053551/191937125-dc32c73c-0f8a-4b5d-bbb9-5a36365b1bd1.png)

**Comment by caiyuanhao1998** [comment]
Please refer to Sec.4.3 of the following repo for HSI visualization.

https://github.com/caiyuanhao1998/MST

**Comment by lzw-lzw** [comment]
> 读进来的mat数值是0-1，uint8好像会把数值全部变为0，所以图像是黑的，把uint8去掉试试

**Comment by ljf20122010** [comment]
> Please refer to Sec.4.3 of the following repo for HSI visualization.
> 
> https://github.com/caiyuanhao1998/MST

Thank you, it helps me a lot

**Comment by ljf20122010** [comment]
> > 读进来的mat数值是0-1，uint8好像会把数值全部变为0，所以图像是黑的，把uint8去掉


> > 读进来的mat数值是0-1，uint8好像会把数值全部变为0，所以图像是黑的，把uint8去掉试试

成功了，谢谢大佬

**Comment by caiyuanhao1998** [comment]
OK，如果想做到论文中的可视化，按照波长来染色的效果就参考我们MST中的代码就好。

**Comment by caiyuanhao1998** [comment]
这个是变量名，需要你自己改一下。
而且这个可视化是28通道的，这也需要改一改。
