### ISSUE TITLE
AWAN Cube shape

### ISSUE THREAD

**Issue by edwinyklau** [caiyuanhao1998/MST-plus-plus#19]
AWAN pretrained model的reconstructed .mat的cube是246x276x31，跟Ground truth的482x512x31不一样
可是MRAE, RMSE, PSNR显示正确，应该如何处理呢?

**Comment by caiyuanhao1998** [comment]
不用处理，他的测试就是截出这么一块 246x276x31 来计算各种指标。官方就是这么测试的，没问题。

**Comment by edwinyklau** [comment]
好的，謝謝

**Comment by caiyuanhao1998** [comment]
嗯嗯，不客气
