### ISSUE TITLE
MAT++ SAB

### ISSUE THREAD

**Issue by mangguo98** [caiyuanhao1998/MST-plus-plus#20]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/87507722/197664885-60ead03f-548e-4f70-b142-508cf1764cf1.png">
您好，想问一下，这里MSAB是否缺少了一个layernorm?
<img width="160" alt="image" src="https://user-images.githubusercontent.com/87507722/197665044-fe029017-371b-489e-9e02-b64db39eb37a.png">

**Comment by caiyuanhao1998** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/48472661/197667673-750822f8-aa2c-4491-9d2a-5ed7e55a1ca8.png">

你好，另一个LN我们放在了MS-MSA里面了

**Comment by mangguo98** [comment]
啊原来是这样！太感谢了 ！

**Comment by caiyuanhao1998** [comment]
嗯嗯，如果你觉得我们的代码有用的话，帮忙点点star

**Comment by mangguo98** [comment]
好的，没问题

**Comment by caiyuanhao1998** [comment]
感谢

**Comment by mangguo98** [comment]
后续有问题再向您请教～

**Comment by caiyuanhao1998** [comment]
嗯嗯

**Comment by mangguo98** [comment]
您好，打扰您了，在我复现的时候我输入了我的数据集 260*64*64 cropsize32，但是在
<img width="518" alt="image" src="https://user-images.githubusercontent.com/87507722/200099578-c4834270-1604-4446-9dda-daf2c128b50a.png">出现了错误，
<img width="569" alt="image" src="https://user-images.githubusercontent.com/87507722/200099614-421eb18b-c617-4707-b694-6bbcd76f2080.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/87507722/200099624-40df4873-7532-48a0-ae94-04081a941e21.png">
但是没有找相关label如何修改的地方，想向您请教一下～～

**Comment by lazyn1997** [comment]
通道数不一致，数据配错了吧，labels不是高光谱，或者模型输出通道数没设置正确

**Comment by dongruoyu1** [comment]
> 您好，打扰您了，在我复现的时候我输入了我的数据集 260_64_64 cropsize32，但是在 <img alt="image" width="518" src="https://user-images.githubusercontent.com/87507722/200099578-c4834270-1604-4446-9dda-daf2c128b50a.png">出现了错误， <img alt="image" width="569" src="https://user-images.githubusercontent.com/87507722/200099614-421eb18b-c617-4707-b694-6bbcd76f2080.png"> <img alt="image" width="348" src="https://user-images.githubusercontent.com/87507722/200099624-40df4873-7532-48a0-ae94-04081a941e21.png"> 但是没有找相关label如何修改的地方，想向您请教一下～～

您好，请问您训练成功了吗

**Comment by lazyn1997** [comment]
模型输出通道数与label通道数不一致，将模型的out_channels, n_feat修改为64，同时MST前三个参数修改为64即可以运行

**Comment by Matsuri247** [comment]
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/56073360/51eae03c-71b6-4a05-be73-171edc1df26c)
作者您好，这里我有疑问，这个地方不是在做l2范数归一化吗？如果按照上面您的说法，那l2范数归一化为什么能够等同于layernorm呢？而且为什么在代码实现上不直接用layernorm呢？
