### ISSUE TITLE
关于训练代数

### ISSUE THREAD

**Issue by Matsuri247** [caiyuanhao1998/MST-plus-plus#21]
您在论文里写的训练epoch是300，但为什么代码里是300*1000呢？还有为什么是取每20个epoch显示一次信息？我不会写训练代码，想学习学习，看得很困惑，希望能解答
![Snipaste_2022-11-17_13-07-19](https://user-images.githubusercontent.com/56073360/202361254-f6fcb8e3-f051-4f8b-a7ae-9946915cf6a2.jpg)
![Snipaste_2022-11-17_13-07-30](https://user-images.githubusercontent.com/56073360/202361263-a7d6bc40-9c6b-4fd9-b64d-d1b56ce4ed25.jpg)

**Comment by Matsuri247** [comment]
这里iteration的数据量，您是直接指定成1000？如果我没理解错的话，一个epoch应当要跑遍整个训练集，单个epoch的数据量=batch_size*iteration，所以iteration应该是在batch_size指定之后算出来的。我猜测这是因为您切块比较密集（stride=8），导致真要跑一个epoch的数据量会特别大，训练300 epoch会特别耗时，是这样吗？

**Comment by caiyuanhao1998** [comment]
你好，1000是因为有1000个数据对，一个epoch要遍历所有的数据对。
每20个epoch打印信息，你也可以改成10个，5个，这个随意。

**Comment by Matsuri247** [comment]
我还是不明白，我讲讲我看完源码的理解，您看看我哪里理解有错：由于切块，每对RGB-HSI数据都被分解成大量128*128的数据对，最后整个数据集总计含有1977885对切块数据。batch_size=20，那么我一个iteration取的就是20对切块数据，按您所说的一个epoch（1000 iteration）就只取了20000对切块数据，并没有遍历整个数据对。我觉得好奇怪

**Comment by Matsuri247** [comment]
我还是不明白，我讲讲我看完源码的理解，您看看我哪里理解有错：由于切块，每对RGB-HSI数据都被分解成大量128*128的数据对，最后整个数据集总计含有1977885对切块数据。batch_size=20，那么我一个iteration取的就是20对切块数据，按您所说的一个epoch（1000 iteration）就只取了20000对切块数据，并没有遍历整个数据对。我觉得好奇怪
![Snipaste_2022-11-17_19-22-32](https://user-images.githubusercontent.com/56073360/202435115-ead27aa2-cea7-43d4-873b-81bb577f38d6.jpg)
![Snipaste_2022-11-17_19-22-53](https://user-images.githubusercontent.com/56073360/202435125-33121305-3170-4c3d-8b13-ae6e595decc2.jpg)

**Comment by caiyuanhao1998** [comment]
不好意思，我搞错了，这个设置就是大概估算一下，所有的iteration走完大概遍历四次数据。

![屏幕快照 2022-11-17 下午7 59 51](https://user-images.githubusercontent.com/48472661/202440866-2f4c50b3-ed7a-48ff-b459-b59e534d3727.png)

**Comment by Matsuri247** [comment]
哦哦那我理解没问题，跟我这边计算的确实对上号了，1977885对切块数据，每次取20对切块数据，总计需要1977885/20=98894.25个iteration，300000*98894.25约等于3，遍历了3次数据。我想是因为切块数过多，所以不便于真的遍历300次数据对吧（过拟合之类的），但论文里似乎没说清楚......只说了300 epoch

**Comment by caiyuanhao1998** [comment]
主要还是比较费时间，你可以试一下，比如一个epoch遍历一次数据，搞个20epoch看看会怎样

**Comment by Matsuri247** [comment]
对确实费时间，我是打算把切的patch_size和stride改了试试...谢谢了，解决了一个大疑问

**Comment by caiyuanhao1998** [comment]
嗯嗯，祝好运
