### ISSUE TITLE
Can't download training spectral images

### ISSUE THREAD

**Issue by fitrirahmah** [caiyuanhao1998/MST-plus-plus#22]
Hello, I can't download the training spectral images. It keeps saying no permission to download. what should I do? thanks for the help

**Comment by caiyuanhao1998** [comment]
Hi! I have tried the link in "2. Data Preparation" and it works. You can also use the competition website or the following git repo to download the dataset:

https://github.com/boazarad/ARAD_1K
https://github.com/boazarad/NTIRE2022_spectral

**Comment by fitrirahmah** [comment]
Thank you, it works
