### ISSUE TITLE
Pred in show_line.m

### ISSUE THREAD

**Issue by fitrirahmah** [caiyuanhao1998/MST-plus-plus#23]
Hello, thanks for sharing your amazing works.
I've run the show_simulation.m, and it works.
But when I've tried to run the show_line.m code in visualization folder, I got an error in 'pred' in line 6. What does pred mean?
Also in line 24, matlab doesn't know what is 'truth'.
Is there any file or toolbox that needs to be installed?

**Comment by caiyuanhao1998** [comment]
Thanks for your support!

The 'pred' and 'truth' are just the names of the matrix variants in the loading mat file. 
'pred' means the predicted HSIs. 'truth' means the ground-truth HSIs.
You may need to change them according to your situation.

There is no need to install any toolbox.

**Comment by fitrirahmah** [comment]
How long does it take to get the plot spectrum? I've run for 1 hour but the matlab is still busy.
My 'pred' and 'truth' matrix are 4-D single. Is it right or not?

**Comment by caiyuanhao1998** [comment]
soon. You can download our predict results and ground-truth to debug.

**Comment by fitrirahmah** [comment]
I've successfully run the program. Thank you for helping!
