### ISSUE TITLE
From the second batch or several batch,  wht the output will be like this?

### ISSUE THREAD

**Issue by langxiujuan** [caiyuanhao1998/MST-plus-plus#26]
![图片](https://github.com/caiyuanhao1998/MST-plus-plus/assets/46564329/cc24d836-d481-405c-bd6a-cda8540c12cf)
the output is blank. Thank you!

**Comment by caiyuanhao1998** [comment]
How did you train the MST++ model?

**Comment by langxiujuan** [comment]
I use CAVE dataset
 
train_sepc: &nbsp; &nbsp;  shape:  31*512* 512 &nbsp;&nbsp;   type: .mat
 
train_RGB:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; shape:  3 *512* 512 &nbsp; &nbsp;    type: .bmp
 
And I changed the network nothing. I changed the his_dataset.py to read my CAVE data. What is the problem? Why the output of feature map  is Nan?



 
The feature map geted from self.conv_in() will be Nan after one or several batch.



load my dataset
 



 

西兰花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caiyuanhao1998/MST-plus-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月13日(星期六) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caiyuanhao1998/MST-plus-plus] From the second batch or several batch,  wht the output will be like this? (Issue #26)





 
How did you train the MST++ model?

**Comment by caiyuanhao1998** [comment]
Did you make sure that the data you read is OK? I suggest you to check the value range of the loaded numpy data, and the n the transferred tensor data. Align the value range with that of NTIRE 2022 data. I saw some other papers successfully did this experiment on CAVE dataset.

**Comment by caiyuanhao1998** [comment]
this dataset is preprocessed by Boaz Arad, not me. I do not have the preprocessing code. All my code has been made public.

I suggest you:

(i) Align the value range of the two dataset using normalization strategy.

(ii) Use another code base for CAVE dataset with our MST++ model.
