### ISSUE TITLE
show_line.m运行出现问题

### ISSUE THREAD

**Issue by Yukijudali** [caiyuanhao1998/MST-plus-plus#27]
您好，当我使用预测得到的高光谱数据运行show_line.m时，会弹出figure123且程序一直显示正忙。当我关闭figure123或者双击figure123的某个区域时会报错，我尝试了一些方法但都没有成功，请问该如何解决呢？

**Comment by caiyuanhao1998** [comment]
我没明白你说的啥意思，可以说得具体一点吗？有没有截图之类的？我这边都可以正常运行呀。

**Comment by caiyuanhao1998** [comment]
你好，我没有看到截图，请问在哪呀？

**Comment by caiyuanhao1998** [comment]
hello, 请问你的问题解决了吗？

**Comment by Yukijudali** [comment]
不好意思，之前发送的太赶了，您看这样能否看得到截图呢？

Figure123的样子是这样的，显示其为512x31的single类型的矩阵。后续我在鼠标选定区域剪切的时候发现无论怎么操作都会报错。除此之外，我输入的预测数据均是482x512x31、single类型的数据。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caiyuanhao1998/MST-plus-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caiyuanhao1998/MST-plus-plus] show_line.m运行出现问题 (Issue #27)





 
hello, 请问你的问题解决了吗？

**Comment by Yukijudali** [comment]
![f23a12866085ef67633d7aa3f79d176](https://github.com/caiyuanhao1998/MST-plus-plus/assets/97288657/05cbd6fe-7e45-4298-989f-fa9113da1553)

**Comment by caiyuanhao1998** [comment]
你测试自己的数据，有GT吗？没有GT没法运行这个程序的。

**Comment by caiyuanhao1998** [comment]
这个show line需要ground-truth来计算选定区域内的相关系数

**Comment by Yukijudali** [comment]
有GT的，代码的内容包括路径我没有进行改动，只是输入进去的除了GT之外的数据使用的是我用您的预测代码生成的，我使用了MPRNET、MIRNET、HDNET、MST以及MST++这五个算法生成的高光谱数据，生成的数据关键词也按照您的代码改成了“truth”和“pred”。

**Comment by caiyuanhao1998** [comment]
报错的信息是什么，figure的图的size貌似也不对。你截图后，记录一下rect2crop的位置。然后把这个rect2crop设置成一个固定值，再跑这个程序。
