### ISSUE TITLE
定量指标与原文不符

### ISSUE THREAD

**Issue by yinghanguan** [caiyuanhao1998/MST-plus-plus#29]
感谢分享，我使用了该代码在所提供得预训练模型中推理得到得定量指标与原文不符，请问是什么问题所导致得呢？
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/62784838/593f188d-0111-48ac-829f-7ae886d5381a)

**Comment by caiyuanhao1998** [comment]
同学你好，请参考我们对这个[issue](https://github.com/caiyuanhao1998/MST-plus-plus/issues/4)的解答，这位网友遇上了和你一样的问题。简单说就是你的torch版本不对导致psnr计算出了问题。

**Comment by yinghanguan** [comment]
感谢解答，请问在论文中得Figure.5中展示了重建得结果，我在所提供得matlab代码中导出了GT的RGB可视化图像，发现与论文中所展示得不一样，请问是由于什么原因所导致得呢？
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/62784838/4ae7faa2-01ff-4cf9-b559-4fa7cb6b7ba3)

**Comment by caiyuanhao1998** [comment]
波长设置不对，需要修改成它制定好的波段范围。那个代码只是一个示范。

**Comment by yinghanguan** [comment]
请问是否可以提供Fig.5中设置的波长参数以及调试过程？

**Comment by caiyuanhao1998** [comment]
请参考NTIRE官网的波长参数，不需要额外调试
