### ISSUE TITLE
 Why not use a random crop?

### ISSUE THREAD

**Issue by yhy258** [caiyuanhao1998/MST-plus-plus#30]
First of all, thanks for sharing the code.

It was found that the Dataset code brings data uniformly based on a certain stride and patch size.

Random cropping is usually used for the task of reconstructing spatial information of an RGB image. Is there a reason for using a uniform patch image in this code?

**Comment by caiyuanhao1998** [comment]
crop by steps can generate more patches, which means the model can be trained by more image pairs.

In fact, crop by steps performs better than random crop in this task. We experimentally verified this point.
