### ISSUE TITLE
数据多次导入

### ISSUE THREAD

**Issue by lazyn1997** [caiyuanhao1998/MST-plus-plus#31]
我在训练时遇到了一个很基础的问题，数据会 load 3次，将 main 上方代码放到 main 函数中，数据就只导入一次，应该是哪里调用了 train.py，但是我没有找到，请问你们运行有这样的问题吗

**Comment by caiyuanhao1998** [comment]
train.py 里面的 main() 函数本身不会加载数据，只是使用了dataloader函数来对加载好的数据分batch来进行快速迭代。load data是在 30 - 35 行。我们没遇到你所说的这个问题。

**Comment by lazyn1997** [comment]
我直接使用```python train.py```执行训练，下面的代码会执行3次，如下图所示，所以是不是有导入的库调用了train.py，因为导入数据的代码不在函数中，所以只要import train，load data就会执行，我将这段代码放置到main函数中，再次运行就只导入一次了，但是我没有找到问题在哪
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/34644177/c2c02dbe-545a-4789-9a5c-9b9ff5c540a5)
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/34644177/0841f3c6-f064-4701-b4f0-77acc52d79ed)

**Comment by caiyuanhao1998** [comment]
<img width="607" alt="截屏2023-09-21 下午9 25 22" src="https://github.com/caiyuanhao1998/MST-plus-plus/assets/48472661/44573e1e-f15b-438a-91b2-fbd57f2a4cf6">

我给你出个debug的主意
from pdb import set_trace as stx
然后在上面这几个包的下边分别打上断点
stx()
然后执行，你看一下执行到导入哪一个包，会load data就知道问题出在哪里了。
我这边看是没找到。你可以排查一下。

**Comment by lazyn1997** [comment]
我又搜了一下，发现这是 Windows 的问题，当 num_workers 设置不为 0 时，系统就会在各个核上面分别执行 train 中不在 ```if __name__ == '__main__':``` 中的代码，因为你的默认 num_workers 为 2，他就是在 2 个核上分别执行了代码，加上最初调用的执行，一共执行了 3 次，而且每个 epoch 都会再次执行 load 数据，生成保存文件夹等操作，所以我将这段代码放到 main 函数中就解决了，十分感谢你的回复。

**Comment by caiyuanhao1998** [comment]
好的，如果觉得我们的代码有用的话，麻烦点点star fork支持一下

**Comment by lazyn1997** [comment]
好的好的
