### ISSUE TITLE
σj Parameter Usage

### ISSUE THREAD

**Issue by Factral** [caiyuanhao1998/MST-plus-plus#32]
I am writing to seek clarification on the implementation of the σj parameter as described in your paper. The paper mentions that σj is used to adapt the multiplication of K (key) and Q (query) matrices and suggests that this adaptation occurs for each wavelength. 

![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/74687828/fa622621-2a25-4252-855b-c3c5792cd370)

However, upon reviewing the code, I noticed that the implementation uses 1 and 2 heads for the respective calculations

https://github.com/caiyuanhao1998/MST-plus-plus/blob/179a9a2d8521bc8ebbfa2557071b2c717f141013/train_code/architecture/MST_Plus_Plus.py#L101

https://github.com/caiyuanhao1998/MST-plus-plus/blob/179a9a2d8521bc8ebbfa2557071b2c717f141013/train_code/architecture/MST_Plus_Plus.py#L130

and the σj is the same for all wavelengths in a head

I am trying to reconcile the implementation details with the description provided in the paper, and any additional insight you could provide would be greatly appreciated.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. Please note that $\sigma_j$ in the paper is constant and the $\sigma$ in the code is a head-dimension vector. It means that for each channel (wavelength), we use a different $\sigma$.

If you find our repo helpful, please help us star it. Thanks.

**Comment by Factral** [comment]
> Hi, thanks for your interest. Please note that σj in the paper is a constant and the σ in the code is a head-dimension vector. It means that for each channel (wavelength), we use a different σj.
> 
> If you find our repo helpful, please help us star it. Thanks.

Okey. However, that would be the case if "heads" were equal to the number of channels, which isn't the case in the code since 1 and 2 heads are used respectively for each SAB, not?
