### ISSUE TITLE
Params and FLOPS evaluating function请问在哪个文件中呀

### ISSUE THREAD

**Issue by Deep-imagelab** [caiyuanhao1998/MST-plus-plus#34]
我找了一下没找到

**Comment by caiyuanhao1998** [comment]
<img width="868" alt="截屏2023-11-08 下午8 22 59" src="https://github.com/caiyuanhao1998/MST-plus-plus/assets/48472661/e2cfe1ca-b332-4fbb-8f2c-bde755408e76">
在这里

**Comment by caiyuanhao1998** [comment]
readme 里面有
