### ISSUE TITLE
数据集处理疑问

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST-plus-plus#35]
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/bd3ef0b1-cf32-4b3c-b26b-c85db0aebf23)
您好，在阅读您的代码时，发现了对训练集加载的时候，有这样两段代码。不是很理解他的用意，我计算得self.patch_per_img为2205，那么每一张图片的索引为什么会是idx//self.patch_per_img？而idx从0-900，那岂不是img_idx都是0了。
img_idx, patch_idx = idx//self.patch_per_img, idx%self.patch_per_img  
h_idx, w_idx = patch_idx//self.patch_per_line, patch_idx%self.patch_per_line

**Comment by caiyuanhao1998** [comment]
每张图片切成多个patch，
训练的instance是一个patch

如果觉得有帮助的话，帮我们点点 star 支持一下
