### ISSUE TITLE
test评价

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST-plus-plus#36]
您好，在test代码中，用训练好的模型去测试50张RGB图像，得到的高光谱图像后发现只将其保存为了mat文件，并没有和label进行比对计算loss等等，请问是为什么呢？

**Comment by caiyuanhao1998** [comment]
*因为

**Comment by dongruoyu1** [comment]
谢谢您的解答！
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/34debba1-c982-4efd-9831-49a500e8592f)
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/8d9b98c0-0961-4f6e-849b-86929a27c389)
有一个小疑惑，您在读取高光谱图像的时候，读取到cube高光谱立方体，立方体的形状为482*512*31，然而您通过hyper = np.transpose(hyper, [0, 2, 1])将其变为了（482，31，512）是否有误？我觉得应该是hyper = np.transpose(hyper, [2, 0, 1])，将形状变为（31，482，512），这样后续才能和label进行比对，您看我说的对吗？
