### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST-plus-plus#37]
![8A341447B610373F24AFC2D426950746](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/2351d36b-4e63-4bcd-bf68-cc03a330ad08)
您好，我将31通道改为28通道，训练自己的数据集，结果却出现了train_losses.avg非常奇怪，甚至等于nan的情况，您有遇到过这种问题吗？

**Comment by caiyuanhao1998** [comment]
emmm，没有，建议你先对自己的数据集来一次 normalization，再训练

**Comment by dongruoyu1** [comment]
> emmm，没有，建议你先对自己的数据集来一次 normalization，再训练

数据集我用的您在mst文章中的30张cave_512，我找到了对应的RGB图像进行训练，也按照您在mst中的步骤，将其归一化了
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/64818568-ec61-4f99-9fa8-2f151037f9b0)
然而误差太奇怪了
