### ISSUE TITLE
关于数据集处理是否有误

### ISSUE THREAD

**Issue by dongruoyu1** [caiyuanhao1998/MST-plus-plus#38]
您好，我有一个小疑惑，如图所示您在读取高光谱图像的时候，读取到cube高光谱立方体，立方体的形状为48251231，然而您通过hyper = np.transpose(hyper, [0, 2, 1])将其变为了（482，31，512）是否有误？我觉得应该是hyper = np.transpose(hyper, [2, 0, 1])，将形状变为（31，482，512），这样后续才能和label进行比对，您看我说的对吗？
![ed39a5bd1d65361e7139aebb7b486dc](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/dfb370d9-eb40-4424-a40f-320f4881cf72)
![1e249b527a97eb974550c9f461b3d70](https://github.com/caiyuanhao1998/MST-plus-plus/assets/128362316/81f432ef-d7dc-4dd3-b0ee-a78d26d7d591)

**Comment by caiyuanhao1998** [comment]
我们的数据处理方式是正确的，别担心
