### ISSUE TITLE
关于layernorm的疑问

### ISSUE THREAD

**Issue by Matsuri247** [caiyuanhao1998/MST-plus-plus#39]
<img width="792" alt="197667673-750822f8-aa2c-4491-9d2a-5ed7e55a1ca8" src="https://github.com/caiyuanhao1998/MST-plus-plus/assets/56073360/58367905-99b7-470a-9a79-0245989352c4">
作者您好，根据您在 https://github.com/caiyuanhao1998/MST-plus-plus/issues/20 中的回答，这部分等同于layernorm，但是这个地方不是在做l2范数归一化吗？l2范数归一化在这里为什么能够等同于layernorm？为什么在代码实现上不直接用layernorm呢？希望您能够帮助我解惑，谢谢

**Comment by caiyuanhao1998** [comment]
在最后一个维度（channel）上做归一化就是 layernorm，直接用 layernorm 也行
