### ISSUE TITLE
关于预测，请问需要多大显存的GPU？

### ISSUE THREAD

**Issue by Howdy1218** [caiyuanhao1998/MST-plus-plus#40]
您好，感谢您的分享，我想使用您预训练的模型对自己的RGB图片进行测试，图片在5M左右，请问8G的显存足够吗？还有就是CUDA和pytorch版本使用最新的版本会不会导致冲突？

**Comment by caiyuanhao1998** [comment]
8g够了，可以试一下最新版本，不过最好还是使用推荐的环境

如果觉得有帮助的话，帮我们点点star支持一下

**Comment by Howdy1218** [comment]
好的，非常感谢！我刚刚试了一下最新版本的，在处理较大图片的时候出现了“RuntimeError: FIND was unable to find an engine to execute this computation”的错误，几十K的图片则没有这个问题，我想应该还是要用推荐环境，再次感谢回答！
