### ISSUE TITLE
训练自己的数据集，train_losses.avg和MRAE很高

### ISSUE THREAD

**Issue by islz** [caiyuanhao1998/MST-plus-plus#41]
![image](https://github.com/caiyuanhao1998/MST-plus-plus/assets/30954004/45b1633d-6475-420d-86d4-2d05ed51dad0)
对数据进行归一化处理了，想请教一下这个大概是因为什么问题造成的？非常感谢！

**Comment by caiyuanhao1998** [comment]
数据集本身做的有问题

**Comment by yuantianhao1** [comment]
@islz 我最近也打算自己做一个数据集。如果方便可以交流一下数据集细节问题。我的QQ是871394709
