### ISSUE TITLE
训练公平性比较

### ISSUE THREAD

**Issue by lijun2005** [caiyuanhao1998/MST-plus-plus#42]
学长您好，看了学长的论文，论文中这些图中的其他模型都是学长自己在NTIRE2022的数据集上重新训练和测试的吗？同时在项目中看到学长在训练这些网络时候的实验设置并不是完全一致的，比如学习率的设置。请问实验设置并不一致的情况下进行实验对比，这对其他模型来说是否公平呢？比如，有可能其他模型比如Restormer在另一个实验设置下表现更好，但是学长自己训练的时候没有把Restormer训练到最佳。
<img width="897" alt="image" src="https://github.com/caiyuanhao1998/MST-plus-plus/assets/118330699/ac0d0508-5b87-4d2d-851e-bb1ebc2ea648">

**Comment by caiyuanhao1998** [comment]
当时是直接参照原文的 setting 去训练，在一个框架下复现如此之多的方法本身是一个工程量很大的任务，很难做到每一个方法都训练到最好，这个问题不大。

如果觉得我们的repo有帮助的话，请帮我们点点star支持一下
