### ISSUE TITLE
Unable to reconstruct RGB from HSI

### ISSUE THREAD

**Issue by beatreichenbach** [caiyuanhao1998/MST-plus-plus#43]
Hello,

Thank you so much for sharing your work! This looks super interesting.

I'm trying to use your algorithm for a VFX implementation to do a round trip from RGB -> HSI -> RGB.
I'm using the model `mst_plus_plus.pth` provided from Google Drive with the code provided here: https://github.com/caiyuanhao1998/MST-plus-plus/blob/master/predict_code/test.py

I'm then converting the HSI to RGB using the `CIE (2006) 10-deg` but also tried `CIE_1964` from this repo by adding up the values for all wavelengths:
```python
# spectral_array is the output from the prediction code.
height, width, lambda_count = spectral_array.shape
lambda_values = np.linspace(400, 700, lambda_count)
image_shape = (height, width, 3)
output = np.zeros(image_shape, np.float32)
for w in range(lambda_count):
    # rgb_dict is the ciexyz values
    rgb = rgb_dict[lambda_values[w]]
    for y in range(height):
        for x in range(width):
            output[y, x] += rgb * spectral_array[y, x, w]
```

I'm simply add up all the different colors from all 31 wavelengths and saving out the file after converting the `CIE-XYZ-D65` to `sRGB` color space.
Unfortunately the resulting rgb values are about 16 times brighter, and don't really match up. I attached a reconstructed rgb image with reduced intensity (`output /= 16`).

The colors definitely match, so the overall distribution seems pretty good, but the intensity does not seem accounted for. Is there anything to consider to be able to reconstruct an image and preserve the intensity?

![input](https://github.com/caiyuanhao1998/MST-plus-plus/assets/44111292/2ff23ab4-ed90-4111-8831-a095658b9b1a)
![output](https://github.com/caiyuanhao1998/MST-plus-plus/assets/44111292/0e5faea2-7410-4e16-a056-87ee48ef49f7)

**Comment by caiyuanhao1998** [comment]
Hi, naively adding up the HSI channels cannot derive the corresponding RGB image. Please refer to [this repo](https://github.com/boazarad/NTIRE2022_spectral). Boaz Arad provide the code for HSI-to-RGB conversion

**Comment by beatreichenbach** [comment]
Thank you so much for sending me in the right direction.

**Comment by caiyuanhao1998** [comment]
you are welcome. If you found our repo helpful, please help us star it. Thanks
