### ISSUE TITLE
指标问题

### ISSUE THREAD

**Issue by renqi1998** [caiyuanhao1998/MST-plus-plus#46]
您好，十分感谢公布代码，我有一个问题想问一下，我在NTIRE2022上根据你们的代码去跑，为什么MPRNet的精度会比MST++以及MST好呢，同时MST++的精度也会比MST稍微低一点。

**Comment by caiyuanhao1998** [comment]
啊？你是否有按照我们的环境配置和显卡硬件去跑呢？我们这边跑出来的是 MST++ > MST > MPRNet

如果觉得我们的 repo 有用的话，帮忙点点 star，感谢

**Comment by renqi1998** [comment]
可能是显卡的问题，我用的不是3090，所以可能有点区别，感谢
