### ISSUE TITLE
预测得到的高光谱数据结果波长求助

### ISSUE THREAD

**Issue by Howdy1218** [caiyuanhao1998/MST-plus-plus#47]
你好，很抱歉打扰到，请问用提供的MST++预训练模型预测自己的RGB图片得到的高光谱数据的31个波段具体是什么？可以帮忙解答一下嘛？非常感谢！

**Comment by caiyuanhao1998** [comment]
400-700 nm, 间隔为 10 nm

如果觉得我们的repo有用的话，帮忙folk支持一下，感谢
