### ISSUE TITLE
Test Set ground truth 

### ISSUE THREAD

**Issue by Summer60** [caiyuanhao1998/MST-plus-plus#48]
Hello, thanks for your contributions. I didn't find the ground truth "spectra" for the test set. Could you please provide it if you have it by any chance? Thanks!

**Comment by caiyuanhao1998** [comment]
Hi, we provide the link to download the data in the `README.md`.

If you find our repo useful, please help us star it. Thanks.

**Comment by Summer60** [comment]
Thank you for your response. Unfortunately, I couldn't find testing spectral images in readme file. I only found testing RGB images there. Could you please be more specific about the file location?
