### ISSUE TITLE
NaN Issue in Training 

### ISSUE THREAD

**Issue by Summer60** [caiyuanhao1998/MST-plus-plus#49]
Hello, I'm attempting to use your training code to train my own data. My RGB images were generated from [300x of] NTIRE 2022 Challenge Spectra (like yours) but using a different camera's spectral sensitivity. The training process runs for a few hours before encountering NaN errors (please see attached). I've noticed others reporting similar issues. Do you have any insights? Perhaps you could share the code you used to generate RGB images from spectra? This should be straightforward, but let's ensure we're on the same page. Thanks for any help!
<img width="863" alt="Screenshot 2024-08-24 190913_mst" src="https://github.com/user-attachments/assets/542813ae-958b-414a-a3b2-516e6c699716">

**Comment by Summer60** [comment]
As an update, I ran your training code on 300 of your own data points (1, 4, 7, ..., 898) and also got NaN. The only change that I made was num_workers from 2 to 0 to avoid memory issue. Any thoughts? 
![Screenshot 2024-08-25 202909_mst2](https://github.com/user-attachments/assets/7fac6eaa-30ef-47d8-a11f-5a87d35000f1)

**Comment by caiyuanhao1998** [comment]
Hi, I think it is better to follow our setting to perform training and testing :)
