### ISSUE TITLE
制作自己的数据集

### ISSUE THREAD

**Issue by newshu** [caiyuanhao1998/MST-plus-plus#5]
你好，我想制作自己的数据集，但是我从相机的源数据提取mat文件出现了大量的负值，请问你们在处理mat中含有负值有什么方法？
我认为我出现负值是因为对数据的黑白平衡导致
![data](https://user-images.githubusercontent.com/78406638/168008439-407704c9-89d8-40da-ad18-f7911d7a4a28.png)

**Comment by linjing7** [comment]
你好，请问是你这个mat文件存储的是高光谱数据吗？
我们在数据清洗的时候，把含有负值的高光谱mat都去掉了；你也可以考虑，在训练时跳过那些含有负值的patch，这样可以更多的保留一些数据样本，这只需要在train_code/hsi_dataset.py里边进行加入几行代码进行修改。
另外，我们使用的数据集是NTIRE2022 Spectral Recovery官方提供的，具体怎么对raw数据进行处理，你可以请教一下组织者Boaz Arad (boazar@post.bgu.ac.il).

**Comment by newshu** [comment]
对的，这个mat文件就是用来训练的高光谱数据。
并且谢谢你的建议。
